### ISSUE TITLE
not set java home

### ISSUE THREAD

**Issue by qianmoQ** [Jaraxal/ambari-elasticsearch-service#4]
`Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.4/services/ELASTICSEARCH/package/scripts/master.py", line 175, in <module>
    Master().execute()
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 280, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.4/services/ELASTICSEARCH/package/scripts/master.py", line 151, in start
    self.configure(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.4/services/ELASTICSEARCH/package/scripts/master.py", line 113, in configure
    Execute(cmd)
  File "/usr/lib/python2.6/site-packages/resource_management/core/base.py", line 155, in __init__
    self.env.run()
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 160, in run
    self.run_action(resource, action)
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 124, in run_action
    provider_action()
  File "/usr/lib/python2.6/site-packages/resource_management/core/providers/system.py", line 273, in action_run
    tries=self.resource.tries, try_sleep=self.resource.try_sleep)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 70, in inner
    result = function(command, **kwargs)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 92, in checked_call
    tries=tries, try_sleep=try_sleep)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 140, in _call_wrapper
    result = _call(command, **kwargs_copy)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 293, in _call
    raise ExecutionFailed(err_msg, code, out, err)
resource_management.core.exceptions.ExecutionFailed: Execution of '/opt/elasticsearch/bin/elasticsearch-plugin remove x-pack' returned 1. which: no java in (/usr/sbin:/sbin:/usr/lib/ambari-server/*:/usr/sbin:/sbin:/usr/lib/ambari-server/*:/sbin:/bin:/usr/sbin:/usr/bin:/var/lib/ambari-agent:/var/lib/ambari-agent)
Could not find any executable java binary. Please install java in your PATH or set JAVA_HOME`

**Comment by YUHAI0** [comment]
I have the same error when I install this ambari service. Can anyone resolve this ?
